debug: true
host: https://localhost
algorithm: Argon2

gin:
  mode: debug #release
  port: 8081

register:
  skipemailverify: false # 邮箱服务器有时会限制，密集发送邮件可能失败。这里增加一个开关，为true时不校验邮箱验证码
  timeout:
    email: 15
    sms: 15

appauth:
  skipauth: false # 调试环境中设置为true可方便调试，产品环境中请设置为false
  tokenexpire: 60 # jwt过期时间，单位是分钟
  authkey: "S5K#GSD8Z1LO0"

app:
  latestapkvercode: 3
  latestapkvername: 1.0.4
  latestapkurl: "http://13.250.12.109:8086/app/app_v1.0.3_2019-01-10-52.apk"

email:
  sender: noreply@yuudidi.com
  password: yuudidi@123
  smtpsvr: smtp.office365.com:587

sms:
  tencent:
    sdkappid: "1400169917"
    appkey: "89e0c46472589dde1d6bd441cca4d634"
    tplid: 244741

storage:
  aliyun:
    endpoint: "http://oss-ap-southeast-1.aliyuncs.com"
    accesskeyid: "LTAIKQ4TyP9nmLfw"
    accesskeysecret: "4I7LeHziL6w3LF7sZw1jzJukdlCObT"
    bucketname4qrcode: "yuudidi-qrcode-test" # 请确保这个bucket为公开可访问

qrcode:
  decodesvcendpoit: "http://localhost:8087/qrcode-tool/api/svc/upload" # 这个服务可以得到二维码图片中的金额、二维码decode后的字符串等信息
  savelocally: false # 是否把二维码保存到本地文件系统，本地路径由 imgpath 配置
  # imgpath: /Users/jack/go/src/yuudidi.com/img
  imgpath: /home/ec2-user/img # 这个参数仅当 savelocally 为 true 时，才会使用它
  expectprefix:
    weixin: "wxp://"
    alipay: "https://qr.alipay.com"

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  pass: 1234
  name: otc
  debug: true
  maxidle: 0  # Try to address issue 'invalid connection', see https://github.com/go-sql-driver/mysql/issues/674
  maxopen: 100

log:
  out: console
  # debug warn error fatal  default info
  level: debug

cache:
  redis:
    host: localhost
    port: 6379
    password:
    prefix: otc
  key:
    acceptorder: "accept:order"

background:
  store:
    uri: redis://localhost:6379
    tlscertpath:
    skiptlsverify: true
  connections: 100
  concurrency: 2
  namespace: "yuudidi:"
  interval: 5

websocket:
  url: http://localhost
  port: 8085
  timeout:
    ping: 60
    pong: 80

redirecturl:
  createurl: http://13.250.12.109:8084/b/order/
  reprocessurl: http://13.250.12.109:8084/b/order/

fulfillment:
  retries: 3
  timeout:
    awaitaccept: 10
    notifypaid: 600
    notifypaymentconfirmed: 600
    retry: 2
    accept: 10
    autoconfirmpaid: 60
    transfer: 1800

signswitch:
  sign: "off"
