debug: true
#host: https://localhost
algorithm: Argon2

currencycrypto:
  price:
    buy: 6.35 # 以币商角度
    sell: 6.5 # 以币商角度

banks:
  中国工商银行: 4
  中国农业银行: 5
  中国银行: 6
  中国建设银行: 7
  交通银行: 8
  中国邮政储蓄银行: 9
  中国光大银行: 10
  中国民生银行: 11
  招商银行: 12
  中信银行: 13
  华夏银行: 14
  上海浦东发展银行: 15
  平安银行: 16
  广发银行: 17
  兴业银行: 18
  浙商银行: 19
  渤海银行: 20
  恒丰银行: 21
  汇丰银行(中国): 22
  恒生银行(中国): 23

gin:
  mode: debug #release
  port: 8081

register:
  skipemailverify: false # 邮箱服务器有时会限制，密集发送邮件可能失败。这里增加一个开关，为true时不校验邮箱验证码
  timeout:
    email: 15
    sms: 15

appauth:
  skipauth: false # 调试环境中设置为true可方便调试，产品环境中请设置为false
  tokenexpire: 60 # jwt过期时间，单位是分钟
  authkey: "S5K#GSD8Z1LO0"

app:
  loginfail:
    maxtimes: 3 # 登录失败3次，24小时内不让登录
    lockhours: 24 # 登录失败3次，24小时内不让登录
  latestapkvercode: 3
  latestapkvername: 1.0.4
  latestapkurl: "http://13.250.12.109:8086/app/app_v1.0.3_2019-01-10-52.apk"

email:
  sender: noreply@yuudidi.com
  password: yuudidi@123
  smtpsvr: smtp.office365.com:587

sms:
  tencent:
    sdkappid: "1400169917"
    appkey: "89e0c46472589dde1d6bd441cca4d634"
    tplid:
      register: 244741
      orderaccepted: 264878 # 订单 {1} 已经被您抢到，请尽快处理。
      orderpaid: 264879 # 订单 {1} 已标记付款，请查收是否到帐，到帐请及时确认，未到账5分钟后可以发起申诉。
      orderpaidtimeout: 265477 # 订单 {1} 用户超时未标记付款，您冻结的币已经释放。

storage:
  aliyun:
    endpoint: "http://oss-ap-southeast-1.aliyuncs.com"
    accesskeyid: "LTAIKQ4TyP9nmLfw"
    accesskeysecret: "4I7LeHziL6w3LF7sZw1jzJukdlCObT"
    bucketname4qrcode: "yuudidi-qrcode-test" # 请确保这个bucket为公开可访问

qrcode:
  decodesvcendpoit: "http://localhost:8087/qrcode-tool/api/svc/upload" # 这个服务可以得到二维码图片中的金额、二维码decode后的字符串等信息
  savelocally: false # 是否把二维码保存到本地文件系统，本地路径由 imgpath 配置
  # imgpath: /Users/jack/go/src/yuudidi.com/img
  imgpath: /home/ec2-user/img # 这个参数仅当 savelocally 为 true 时，才会使用它
  expectprefix:
    weixin: "wxp://"
    alipay: "https://qr.alipay.com"

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  pass: 1234
  name: otc
  debug: true
  maxidle: 0 # Try to address issue 'invalid connection', see https://github.com/go-sql-driver/mysql/issues/674
  maxopen: 100

log:
  out: console
  # debug warn error fatal  default info
  level: debug

cache:
  redis:
    host: localhost
    port: 6379
    password:
    prefix: otc
  key:
    acceptorder: "accept:order"

background:
  store:
    uri: redis://localhost:6379
    tlscertpath:
    skiptlsverify: true
  connections: 100
  concurrency: 2
  namespace: "yuudidi:"
  interval: 5

websocket:
  url: http://localhost
  port: 8085
  timeout:
    ping: 50
    pong: 70
    logout: 600

redirecturl:
  createurl: http://13.250.12.109:8084/b/order/
  reprocessurl: http://13.250.12.109:8084/b/order/

fulfillment:
  oneroundsize: 40 # 一轮最多给多少个币商派单
  forbidneworderifunfinished: false   # 如果为true，则币商如果有进行中的订单未完成，就不给它派单
  retries: 3
  officialmerchant:
    retries: 20000
  timeout: # 下面时间单位都为秒
    awaitaccept: 90
    awaitautoorderaccept: 12
    notifypaid: 600 # 付款超时时间
    notifypaymentconfirmed: 900 # 确认对方已付款的超时时间
    retry: 2 # 一轮没找到币商，则sleep这个秒数后，再开始下一轮寻找币商
    accept: 90
    autoconfirmpaid: 60
    transfer: 3600 # 用户提现订单，币商币锁定这个秒数后才解冻
    retrytime: 30 #订单更新失败时将订单修改为suspened状态时的重试时间
    autounfreeze: 2700 #充值订单如果h5用户没有点击我已付款，超时会自动解冻

signswitch:
  sign: "off"

tickettoken:
  token: "1234qwer"

token:
  timeout: 3600

web:
  server:
    secret: 778EA0C5E0B8444E86750888CFEF2948
    timeout: 3600

#excel 表格title
excel:
  A1: 创单时间
  B1: 最后状态时间
  C1: 订单号
  D1: 平台商订单号
  E1: btusd 数额
  F1: rmb 数目
  G1: 买卖
  H1: 交易状态
  I1: 订单异常状态
  J1: 平台商
  K1: 承兑商
  L1: 承兑商电话
  M1: 付款类型
  N1: trader income
  O1: merchant income
  P1: jrdidi income

sendnotifyswitch:
  version: new #回调消息版本，old是老版本，只有status=7有重试机制;new是新版本，使用时间轮定时，所有状态都有重试机制

appidversion: # 下面配置不能修改或删除，如果有修改或删除，那么名单里的这些平台商就会报签名错误，无法访问任何接口
  1: v1.0
  10001: v1.0
  10002: v1.0
  10003: v1.0
  10004: v1.0
  10005: v1.0
  10006: v1.0
  10007: v1.0
  10008: v1.0
  10009: v1.0
  10016: v1.0
  236229119: v1.0  # 下面是13环境
  111222: v1.0
  111231: v1.0
  32227312: v1.0
  32227344: v1.0
  32227300: v1.0
  32227298: v1.0
  32227322: v1.0
  32227345: v1.0
  32227306: v1.0
  111232: v1.0
  32227305: v1.0
  32227304: v1.0
  32227301: v1.0
  111223: v1.0
  5334511: v1.0
  32227299: v1.0
  111233: v1.0
  10089: v1.0
  32227297: v1.0
  32227346: v1.0
  32227311: v1.0
  2334510: v1.0
  3334510: v1.0
  4334510: v1.0
  5334510: v1.0
  100007: v1.0
  32227310: v1.0
  32227307: v1.0
  32227353: v1.0
  32227352: v1.0
  32227351: v1.0
