debug: true
host: https://localhost
algorithm: Argon2

gin:
  mode: debug #release
  port: 8080

register:
  timeout:
    email: 15
    sms: 15

email:
  sender: aaachain@sina.com
  password: aaa2018
  smtpsvr: smtp.sina.com:25

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  pass: 1234
  name: otc
  debug: true

log:
  out: console

background:
  store:
    uri: redis://localhost:6379
    tlscertpath:
    skiptlsverify: true
  connections: 100
  concurrency: 2
  namespace: yuudidi
  interval: 5
