debug: true
host: https://localhost
algorithm: Argon2

gin:
  mode: debug #release
  port: 8081

register:
  skipemailverify: false # 邮箱服务器有时会限制，密集发送邮件可能失败。这里增加一个开关，为true时不校验邮箱验证码
  timeout:
    email: 15
    sms: 15

appauth:
  skipauth: true # 调度环境中设置为true可方便调度，产品环境请设置为false
  authkey: "S5K#GSD8Z1LO0"

email:
  sender: noreply@yuudidi.com
  password: yuudidi@123
  smtpsvr: smtp.office365.com:587

sms:
  tencent:
    sdkappid: "1400169917"
    appkey: "89e0c46472589dde1d6bd441cca4d634"
    tplid: 244741

qrcode:
  #  imgpath: /Users/jack/go/src/yuudidi.com/img
  imgpath: /home/ec2-user/img
  remotesvr: http://13.250.12.109:8086

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  pass: 1234
  name: otc
  debug: true

log:
  out: console

cache:
  redis:
    host: localhost
    port: 6379
    password:
    prefix: otc

background:
  store:
    uri: redis://localhost:6379
    tlscertpath:
    skiptlsverify: true
  connections: 100
  concurrency: 2
  namespace: "yuudidi:"
  interval: 5

websocket:
  url: http://10.2.1.24
  port: 8085

redirecturl:
  createurl: http://13.250.12.109:8084/b/order/
  reprocessurl: http://13.250.12.109:8084/b/order/

fulfillment:
  timeout:
    notifypaid: 600
