debug: true
host: https://localhost

gin:
  mode: debug #release
  port: 8080

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  pass: 1234
  name: otc
  debug: true

log:
  out: console