debug: true
host: https://localhost
algorithm: Argon2

gin:
  mode: debug #release
  port: 8080

register:
  skipemailverify: true # 邮箱服务器有时会限制，密集发送邮件可能失败。这里增加一个开关。
  timeout:
    email: 15
    sms: 15

email:
  sender: aaachain@sina.com
  password: aaa2018
  smtpsvr: smtp.sina.com:25

qrcode:
#  imgpath: /Users/jack/go/src/yuudidi.com/img
  imgpath: /home/ec2-user/img
  remotesvr: http://13.250.12.109:8090

database:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  pass: 1234
  name: otc
  debug: true

log:
  out: console

cache:
  redis:
    host: localhost
    port: 6379
    password:
    prefix: otc

background:
  store:
    uri: redis://localhost:6379
    tlscertpath:
    skiptlsverify: true
  connections: 100
  concurrency: 2
  namespace: yuudidi
  interval: 2

websocket:
  port: 9090
