package app

import (
	"YuuPay_core-service/pkg/api"
	"YuuPay_core-service/pkg/utils"
	"github.com/gin-gonic/gin"
	"os"
	"path"
	"runtime"

	"github.com/swaggo/gin-swagger" // gin-swagger middleware
	"github.com/swaggo/gin-swagger/swaggerFiles" // swagger embed files

	_ "YuuPay_core-service/docs"  // docs is generated by Swag CLI, you have to import it.
)

func RunServer(port string) error {
	defer utils.DB.Close()
	defer utils.Log.OSFile.Close()
	r := gin.Default()

	//store := cookie.NewStore([]byte("secret"))
	//r.Use(sessions.Sessions("session", store))

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.POST("/merchant/login",api.AppLogin)
	r.POST("/merchant/register",api.Register)
	r.GET("/merchant/randomcode",api.GetRandomCode)
	r.POST("/merchant/resetpassword",api.ResetPw)
	r.GET("/merchant/auditstatus",api.GetAuditStatus)

	g := r.Group("/")
	g.Use()
	{

		merchants := g.Group("/merchant")
		{
			merchants.POST("logout", api.AppLogout)
			merchants.GET("profile", api.GetProfile)
			merchants.GET("order", api.GetOrder)
			merchants.PUT("settings/nickname", api.SetNickName)
			merchants.GET("settings/workmode", api.GetWorkMode)
			merchants.PUT("settings/workmode", api.SetWorkMode)
			merchants.GET("settings/identify", api.GetIdentify)
			merchants.PUT("settings/identify", api.SetIdentify)
			merchants.GET("settings/payments", api.GetPayments)
			merchants.POST("settings/payments", api.AddPayment)
			merchants.PUT("settings/payments", api.SetPayment)
			merchants.DELETE("settings/payments", api.DeletePayment)


		}
		g.GET("/order",api.GetOrders)
	}


	_, fileName, _, _ := runtime.Caller(0)
	rootPath := path.Join(fileName, "../../../../configs/")
	err := os.Chdir(rootPath)
	if err != nil {
		panic(err)
	}
	r.Run(":" + port)
	return nil
}