package app

import (
	"YuuPay_core-service/pkg/api/v1"
	"YuuPay_core-service/pkg/api/v1/merchant"
	"YuuPay_core-service/pkg/api/v1/order"
	"YuuPay_core-service/pkg/api/v1/user"
	"YuuPay_core-service/pkg/utils"
	"github.com/gin-gonic/gin"
	"os"
	"path"
	"runtime"

	"github.com/swaggo/gin-swagger" // gin-swagger middleware
	"github.com/swaggo/gin-swagger/swaggerFiles" // swagger embed files

	_ "YuuPay_core-service/docs"  // docs is generated by Swag CLI, you have to import it.
)

func RunServer(port string) error {
	defer utils.DB.Close()
	defer utils.Log.OSFile.Close()
	r := gin.Default()

	//store := cookie.NewStore([]byte("secret"))
	//r.Use(sessions.Sessions("session", store))

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.POST("/merchant/login",v1.AppLogin)
	r.POST("/merchant/register",v1.Register)
	r.GET("/merchant/randomcode",v1.GetRandomCode)
	r.POST("/merchant/resetpassword",v1.ResetPw)
	r.GET("/merchant/auditstatus",merchant.GetAuditStatus)

	g := r.Group("/")
	g.Use()
	{

		merchants := g.Group("/merchant")
		{
			merchants.POST("logout", v1.AppLogout)
			merchants.GET("profile", merchant.GetProfile)
			merchants.GET("order", merchant.GetOrder)
			merchants.PUT("settings/nickname", merchant.SetNickName)
			merchants.GET("settings/workmode", merchant.GetWorkMode)
			merchants.PUT("settings/workmode", merchant.SetWorkMode)
			merchants.GET("settings/identify", merchant.GetIdentify)
			merchants.PUT("settings/identify", merchant.SetIdentify)
			merchants.GET("settings/payments", merchant.GetPayments)
			merchants.POST("settings/payments", merchant.AddPayment)
			merchants.PUT("settings/payments", merchant.SetPayment)
			merchants.DELETE("settings/payments", merchant.DeletePayment)


		}
		g.GET("/order",order.GetOrders)
		g.GET("/user",user.GetUser)
	}


	_, fileName, _, _ := runtime.Caller(0)
	rootPath := path.Join(fileName, "../../../../configs/")
	err := os.Chdir(rootPath)
	if err != nil {
		panic(err)
	}
	r.Run(":" + port)
	return nil
}