// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-12-06 15:15:30.373495 +0800 CST m=+0.077789010

package docs

import (
	"bytes"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/distributors": {
            "get": {
                "description": "坐席获取订单列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台 API"
                ],
                "summary": "获取平台商列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页数",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "订单状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "平台商id",
                        "name": "distributor_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "承兑商id",
                        "name": "merchant_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "筛选开始时间",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "筛选截止时间",
                        "name": "stop_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "筛选字段",
                        "name": "time_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索值",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功（status为success）失败（status为fail）都会返回200",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/distributor.GetDistributorsRet"
                        }
                    }
                }
            },
            "put": {
                "description": "坐席修改平台商信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台 API"
                ],
                "summary": "修改平台商",
                "parameters": [
                    {
                        "description": "输入参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/distributor.UpdateDistributorsArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功（status为success）失败（status为fail）都会返回200",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/distributor.UpdateDistributorsRet"
                        }
                    }
                }
            },
            "post": {
                "description": "坐席创建平台商",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台 API"
                ],
                "summary": "创建平台商",
                "parameters": [
                    {
                        "description": "输入参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/distributor.CreateDistributorsArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功（status为success）失败（status为fail）都会返回200",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/distributor.CreateDistributorsRet"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "用户（承兑商）登录系统",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台 API"
                ],
                "summary": "登录系统",
                "parameters": [
                    {
                        "description": "Login argument",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.LoginArg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功（status为success）失败（status为fail）都会返回200",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.LoginRet"
                        }
                    }
                }
            }
        },
        "/merchant/auditstatus": {
            "get": {
                "description": "获取承兑商账号审核状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "承兑商APP API"
                ],
                "summary": "获取承兑商账号审核状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.GetAuditStatusRet"
                        }
                    }
                }
            }
        },
        "/merchant/login": {
            "post": {
                "description": "用户（承兑商）登录系统",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "承兑商APP API"
                ],
                "summary": "承兑商登录APP",
                "parameters": [
                    {
                        "description": "输入参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.LoginArg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.LoginRet"
                        }
                    }
                }
            }
        },
        "/merchant/logout": {
            "post": {
                "description": "承兑商退出登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "承兑商APP API"
                ],
                "summary": "承兑商退出登录",
                "parameters": [
                    {
                        "description": "输入参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.AppLogoutArg"
                        }
                    }
                ]
            }
        },
        "/merchant/profile": {
            "get": {
                "description": "获取承兑商个人信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "承兑商APP API"
                ],
                "summary": "获取承兑商个人信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.GetProfileRet"
                        }
                    }
                }
            }
        },
        "/merchant/randomcode": {
            "get": {
                "description": "获取随机验证码，通知短信或者邮件发送。这个API在承兑商“重置密码”时使用。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "承兑商APP API"
                ],
                "summary": "获取随机验证码，承兑商“重置密码”时使用",
                "parameters": [
                    {
                        "type": "string",
                        "description": "图形验证码",
                        "name": "v_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "手机号或者邮箱",
                        "name": "account",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.GetRandomCodeRet"
                        }
                    }
                }
            }
        },
        "/merchant/register": {
            "post": {
                "description": "用户（承兑商）注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "承兑商APP API"
                ],
                "summary": "承兑商注册APP",
                "parameters": [
                    {
                        "description": "输入参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.RegisterArg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.RegisterRet"
                        }
                    }
                }
            }
        },
        "/merchant/resetpassword": {
            "post": {
                "description": "重置承兑商密码",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "承兑商APP API"
                ],
                "summary": "重置承兑商密码",
                "parameters": [
                    {
                        "description": "输入参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.ResetPasswordArg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/v1.ResetPasswordRet"
                        }
                    }
                }
            }
        },
        "/merchant/settings/identify": {
            "get": {
                "description": "获取承兑商订单推送模式和开关",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "承兑商APP API"
                ],
                "summary": "获取承兑商订单推送模式和开关",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.GetIdentifyRet"
                        }
                    }
                }
            },
            "put": {
                "description": "承兑商设置自己的认证信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "承兑商APP API"
                ],
                "summary": "承兑商设置自己的认证信息",
                "parameters": [
                    {
                        "description": "用户id",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.SetIdentifyArg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.SetIdentifyRet"
                        }
                    }
                }
            }
        },
        "/merchant/settings/nickname": {
            "put": {
                "description": "设置承兑商昵称",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "承兑商APP API"
                ],
                "summary": "设置承兑商昵称",
                "parameters": [
                    {
                        "description": "用户id",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.SetNickNameArg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.SetNickNameRet"
                        }
                    }
                }
            }
        },
        "/merchant/settings/payments": {
            "get": {
                "description": "获取承兑商的收款账户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "承兑商APP API"
                ],
                "summary": "获取承兑商的收款账户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.GetPaymentsRet"
                        }
                    }
                }
            },
            "put": {
                "description": "修改承兑商的收款账户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "承兑商APP API"
                ],
                "summary": "修改承兑商的收款账户信息",
                "parameters": [
                    {
                        "description": "输入参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.SetPaymentArg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.SetPaymentRet"
                        }
                    }
                }
            },
            "post": {
                "description": "增加承兑商的收款账户信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "承兑商APP API"
                ],
                "summary": "增加承兑商的收款账户信息",
                "parameters": [
                    {
                        "description": "输入参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.AddPaymentArg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.AddPaymentRet"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除承兑商的收款账户信息。需要先确定是否有正在进行的订单，如果有不允许删除。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "承兑商APP API"
                ],
                "summary": "删除承兑商的收款账户信息",
                "parameters": [
                    {
                        "description": "输入参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.DeletePaymentArg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.DeletePaymentRet"
                        }
                    }
                }
            }
        },
        "/merchant/settings/workmode": {
            "get": {
                "description": "获取承兑商订单推送模式和开关",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "承兑商APP API"
                ],
                "summary": "获取承兑商订单推送模式和开关",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "uid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.GetWorkModeRet"
                        }
                    }
                }
            },
            "put": {
                "description": "承兑商设置订单推送模式和开关",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "承兑商APP API"
                ],
                "summary": "承兑商设置订单推送模式和开关",
                "parameters": [
                    {
                        "description": "用户id",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.SetWorkModeArg"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.SetWorkModeRet"
                        }
                    }
                }
            }
        },
        "/merchants": {
            "get": {
                "description": "坐席获取承兑商列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台 API"
                ],
                "summary": "获取承兑商列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页数",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "承兑商状态",
                        "name": "user_status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "筛选开始时间",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "筛选截止时间",
                        "name": "stop_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "筛选字段",
                        "name": "time_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索值",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功（status为success）失败（status为fail）都会返回200",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.MerchantRet"
                        }
                    }
                }
            }
        },
        "/merchants/{uid}/approve": {
            "put": {
                "description": "审核承兑商",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台 API"
                ],
                "summary": "审核",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "充值",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.ApproveArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功（status为success）失败（status为fail）都会返回200",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.ApproveRet"
                        }
                    }
                }
            }
        },
        "/merchants/{uid}/asset": {
            "put": {
                "description": "给承兑商充值",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台 API"
                ],
                "summary": "充值",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "充值",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.RechargeArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功（status为success）失败（status为fail）都会返回200",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.RechargeRet"
                        }
                    }
                }
            }
        },
        "/merchants/{uid}/freeze": {
            "put": {
                "description": "审核承冻结或者解冻",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台 API"
                ],
                "summary": "冻结",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "冻结操作",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.FreezeArgs"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功（status为success）失败（status为fail）都会返回200",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/merchant.MerchantRet"
                        }
                    }
                }
            }
        },
        "/orders": {
            "get": {
                "description": "坐席获取订单列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "管理后台 API"
                ],
                "summary": "获取订单列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页数",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "订单状态",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "平台商id",
                        "name": "distributor_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "承兑商id",
                        "name": "merchant_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "筛选开始时间",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "筛选截止时间",
                        "name": "stop_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "筛选字段",
                        "name": "time_field",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索值",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功（status为success）失败（status为fail）都会返回200",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/order.OrdersRet"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "distributor.CreateDistributorsArgs": {
            "type": "object",
            "required": [
                "api_key",
                "api_secret",
                "name",
                "phone",
                "status",
                "url"
            ],
            "properties": {
                "api_key": {
                    "type": "string",
                    "example": "13112345678"
                },
                "api_secret": {
                    "type": "string",
                    "example": "13112345678"
                },
                "name": {
                    "type": "string",
                    "example": "test"
                },
                "phone": {
                    "type": "string",
                    "example": "13112345678"
                },
                "status": {
                    "type": "integer",
                    "example": 13112345678
                },
                "url": {
                    "type": "string",
                    "example": "13112345678"
                }
            }
        },
        "distributor.CreateDistributorsRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object"
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer",
                    "example": 1001
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "distributor.GetDistributorsRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "data": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Merchant"
                            }
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer",
                    "example": 1001
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "distributor.UpdateDistributorsArgs": {
            "type": "object",
            "required": [
                "api_key",
                "api_secret",
                "name",
                "phone",
                "status",
                "url"
            ],
            "properties": {
                "api_key": {
                    "type": "string",
                    "example": "13112345678"
                },
                "api_secret": {
                    "type": "string",
                    "example": "13112345678"
                },
                "name": {
                    "type": "string",
                    "example": "test"
                },
                "phone": {
                    "type": "string",
                    "example": "13112345678"
                },
                "status": {
                    "type": "integer",
                    "example": 13112345678
                },
                "url": {
                    "type": "string",
                    "example": "13112345678"
                }
            }
        },
        "distributor.UpdateDistributorsRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object"
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer",
                    "example": 1001
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "merchant.AddPaymentArg": {
            "type": "object",
            "properties": {
                "bank": {
                    "description": "所属银行",
                    "type": "string",
                    "example": "工商银行"
                },
                "bank_account": {
                    "description": "银行卡账号",
                    "type": "string",
                    "example": "88888888"
                },
                "bank_branch": {
                    "description": "所属银行分行",
                    "type": "string",
                    "example": "工商银行日本分行"
                },
                "gr_code": {
                    "description": "二维码信息",
                    "type": "string",
                    "example": "xxxx"
                },
                "name": {
                    "description": "账户名",
                    "type": "string",
                    "example": "sky"
                },
                "pay_type": {
                    "description": "支付类型 1:银行卡 2:微信 3:支付宝",
                    "type": "integer"
                },
                "uid": {
                    "description": "承兑商用户id",
                    "type": "integer"
                }
            }
        },
        "merchant.AddPaymentRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "uid": {
                            "description": "用户id",
                            "type": "integer"
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "merchant.ApproveArgs": {
            "type": "object",
            "required": [
                "count",
                "currency",
                "operation"
            ],
            "properties": {
                "count": {
                    "type": "string",
                    "example": "200"
                },
                "currency": {
                    "type": "string",
                    "example": "BTUSD"
                },
                "operation": {
                    "description": "审核操作 1：通过 0：不通过",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "merchant.ApproveRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "data": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Merchant"
                            }
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "merchant.DeletePaymentArg": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "收款账号信息主键",
                    "type": "integer"
                },
                "uid": {
                    "description": "承兑商用户id",
                    "type": "integer"
                }
            }
        },
        "merchant.DeletePaymentRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "uid": {
                            "description": "用户id",
                            "type": "integer"
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "merchant.FreezeArgs": {
            "type": "object",
            "required": [
                "count",
                "currency",
                "operation"
            ],
            "properties": {
                "count": {
                    "type": "string",
                    "example": "200"
                },
                "currency": {
                    "type": "string",
                    "example": "BTUSD"
                },
                "operation": {
                    "description": "冻结操作 1：冻结 0：解冻",
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "merchant.GetAuditStatusRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "contact_phone": {
                            "description": "客服联系信息",
                            "type": "string",
                            "example": "13812341234"
                        },
                        "extra_message": {
                            "description": "额外的信息",
                            "type": "string",
                            "example": "您由于xx原因，未通过审核"
                        },
                        "uid": {
                            "description": "用户id",
                            "type": "integer"
                        },
                        "user_status": {
                            "description": "user_status可以为0/1/2，分别表示“正常/待审核/冻结”",
                            "type": "integer"
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "merchant.GetIdentifyRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "email": {
                            "type": "string",
                            "example": "xxx@xxx.com"
                        },
                        "idcard": {
                            "type": "string",
                            "example": "11088888888888888"
                        },
                        "phone": {
                            "type": "string"
                        },
                        "uid": {
                            "description": "用户id",
                            "type": "integer"
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "merchant.GetPaymentsRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "data": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/merchant.Payment"
                            }
                        },
                        "uid": {
                            "description": "用户id",
                            "type": "integer"
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "merchant.GetProfileRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "asset_frozen": {
                            "description": "当前承兑商被冻结的平台币数量",
                            "type": "string",
                            "example": "100"
                        },
                        "asset_symbol": {
                            "description": "平台币的符号",
                            "type": "string",
                            "example": "BTUSD"
                        },
                        "asset_total": {
                            "description": "当前承兑商所有的平台币余额（包含被冻结的平台币）",
                            "type": "string",
                            "example": "2000"
                        },
                        "nickname": {
                            "description": "用户昵称",
                            "type": "string",
                            "example": "老王"
                        },
                        "uid": {
                            "description": "用户id",
                            "type": "integer"
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "merchant.GetWorkModeRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "accept": {
                            "description": "是否接单(1:开启，0:关闭)",
                            "type": "integer"
                        },
                        "auto": {
                            "description": "是否自动接单(1:开启，0:关闭)",
                            "type": "integer"
                        },
                        "uid": {
                            "description": "用户id",
                            "type": "integer"
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "merchant.MerchantRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "data": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Merchant"
                            }
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "merchant.Payment": {
            "type": "object",
            "properties": {
                "bank": {
                    "description": "所属银行",
                    "type": "string",
                    "example": "工商银行"
                },
                "bank_account": {
                    "description": "银行卡账号",
                    "type": "string",
                    "example": "88888888"
                },
                "bank_branch": {
                    "description": "所属银行分行",
                    "type": "string",
                    "example": "工商银行日本分行"
                },
                "gr_code": {
                    "description": "二维码信息",
                    "type": "string",
                    "example": "xxxx"
                },
                "id": {
                    "description": "主键，无实际意义",
                    "type": "integer"
                },
                "name": {
                    "description": "账户名",
                    "type": "string",
                    "example": "sky"
                },
                "pay_type": {
                    "description": "支付类型 1:银行卡 2:微信 3:支付宝",
                    "type": "integer"
                }
            }
        },
        "merchant.RechargeArgs": {
            "type": "object",
            "required": [
                "count",
                "currency"
            ],
            "properties": {
                "count": {
                    "type": "string",
                    "example": "200"
                },
                "currency": {
                    "type": "string",
                    "example": "BTUSD"
                }
            }
        },
        "merchant.RechargeRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "data": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Merchant"
                            }
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "merchant.SetIdentifyArg": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "xxx@xxx.com"
                },
                "idcard": {
                    "type": "integer"
                },
                "phone": {
                    "type": "string"
                },
                "uid": {
                    "description": "用户id",
                    "type": "integer"
                }
            }
        },
        "merchant.SetIdentifyRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "uid": {
                            "description": "用户id",
                            "type": "integer"
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "merchant.SetNickNameArg": {
            "type": "object",
            "properties": {
                "nickname": {
                    "description": "想设置的新昵称",
                    "type": "string",
                    "example": "王老板"
                },
                "uid": {
                    "description": "用户id",
                    "type": "integer"
                }
            }
        },
        "merchant.SetNickNameRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "uid": {
                            "description": "用户id",
                            "type": "integer"
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "merchant.SetPaymentArg": {
            "type": "object",
            "properties": {
                "bank": {
                    "description": "所属银行",
                    "type": "string",
                    "example": "工商银行"
                },
                "bank_account": {
                    "description": "银行卡账号",
                    "type": "string",
                    "example": "88888888"
                },
                "bank_branch": {
                    "description": "所属银行分行",
                    "type": "string",
                    "example": "工商银行日本分行"
                },
                "gr_code": {
                    "description": "二维码信息",
                    "type": "string",
                    "example": "xxxx"
                },
                "id": {
                    "description": "收款账号信息主键",
                    "type": "integer"
                },
                "name": {
                    "description": "账户名",
                    "type": "string",
                    "example": "sky"
                },
                "pay_type": {
                    "description": "支付类型 1:银行卡 2:微信 3:支付宝",
                    "type": "integer"
                }
            }
        },
        "merchant.SetPaymentRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "uid": {
                            "description": "用户id",
                            "type": "integer"
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "merchant.SetWorkModeArg": {
            "type": "object",
            "properties": {
                "accept": {
                    "description": "是否接单(1:开启，0:关闭)",
                    "type": "integer"
                },
                "auto": {
                    "description": "是否自动接单(1:开启，0:关闭)",
                    "type": "integer"
                },
                "uid": {
                    "description": "用户id",
                    "type": "integer"
                }
            }
        },
        "merchant.SetWorkModeRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "uid": {
                            "description": "用户id",
                            "type": "integer"
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.Assets": {
            "type": "object",
            "properties": {
                "currency_asset": {
                    "type": "string"
                },
                "frozen_quantity": {
                    "type": "number"
                },
                "id": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "number"
                },
                "uid": {
                    "type": "integer"
                }
            }
        },
        "models.Merchant": {
            "type": "object",
            "properties": {
                "asset": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Assets"
                    }
                },
                "avatar_uri": {
                    "type": "string"
                },
                "display_uid": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "payments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.PaymentInfo"
                    }
                },
                "phone": {
                    "type": "string"
                },
                "preferences": {
                    "type": "object",
                    "$ref": "#/definitions/models.Preferences"
                },
                "uid": {
                    "type": "integer"
                }
            }
        },
        "models.Order": {
            "type": "object",
            "properties": {
                "buyer_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "price": {
                    "type": "number"
                },
                "quantity": {
                    "type": "number"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "models.PaymentInfo": {
            "type": "object",
            "properties": {
                "bank": {
                    "type": "string"
                },
                "bank_account": {
                    "type": "string"
                },
                "bank_branch": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "pay_type": {
                    "type": "integer"
                },
                "qrCode": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "uid": {
                    "type": "integer"
                }
            }
        },
        "models.Preferences": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "language": {
                    "type": "string"
                },
                "locale": {
                    "type": "string"
                }
            }
        },
        "order.OrdersRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "data": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Order"
                            }
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "v1.AppLogoutArg": {
            "type": "object",
            "properties": {
                "uid": {
                    "type": "integer"
                }
            }
        },
        "v1.GetRandomCodeRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object"
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "v1.LoginArg": {
            "type": "object",
            "required": [
                "account",
                "password"
            ],
            "properties": {
                "account": {
                    "type": "string",
                    "example": "13112345678"
                },
                "password": {
                    "type": "string",
                    "example": "pwd123"
                }
            }
        },
        "v1.LoginRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "nickname": {
                            "description": "用户昵称",
                            "type": "string",
                            "example": "老王"
                        },
                        "uid": {
                            "description": "用户id",
                            "type": "integer"
                        },
                        "user_cert": {
                            "description": "user_cert可以为0/1，分别表示“已认证/未认证”",
                            "type": "integer"
                        },
                        "user_status": {
                            "description": "user_status可以为0/1/2，分别表示“正常/待审核/冻结”",
                            "type": "integer"
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "v1.RegisterArg": {
            "type": "object",
            "required": [
                "email",
                "password",
                "phone",
                "pic_code",
                "random_code"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "xxx@sina.com"
                },
                "password": {
                    "type": "string",
                    "example": "pwd1234"
                },
                "phone": {
                    "type": "string",
                    "example": "13112345678"
                },
                "pic_code": {
                    "description": "图形验证码",
                    "type": "string",
                    "example": "E87A"
                },
                "random_code": {
                    "description": "随机验证码（通过手机或邮件发送的）",
                    "type": "string",
                    "example": "9823"
                }
            }
        },
        "v1.RegisterRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object",
                    "properties": {
                        "uid": {
                            "description": "用户id",
                            "type": "integer"
                        }
                    }
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "v1.ResetPasswordArg": {
            "type": "object",
            "required": [
                "account",
                "password",
                "pic_code",
                "random_code"
            ],
            "properties": {
                "account": {
                    "description": "所要重置密码的账号名",
                    "type": "string",
                    "example": "13112345678"
                },
                "password": {
                    "description": "所设置的新密码",
                    "type": "string",
                    "example": "pwd1234"
                },
                "pic_code": {
                    "description": "图形验证码",
                    "type": "string",
                    "example": "E87A"
                },
                "random_code": {
                    "description": "随机验证码（通过手机或邮件发送的）",
                    "type": "string",
                    "example": "9823"
                }
            }
        },
        "v1.ResetPasswordRet": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "entity": {
                    "type": "object"
                },
                "err_code": {
                    "description": "err_code仅在失败时设置",
                    "type": "integer"
                },
                "err_msg": {
                    "description": "err_msg仅在失败时设置",
                    "type": "string",
                    "example": "由于xx原因，导致操作失败"
                },
                "status": {
                    "description": "status可以为success或者fail",
                    "type": "string",
                    "example": "success"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo swaggerInfo

type s struct{}

func (s *s) ReadDoc() string {
	t, err := template.New("swagger_info").Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, SwaggerInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
